### ISSUE TITLE
Separate readme files for each workload

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift-scale/workloads#16]
We need to have separate readme files for each workload supported as the length of the readme might be too big as we add more workloads to the repo like @akrzos suggested.

**Comment by akrzos** [comment]
@chaitanyaenr @ekuric @jmencak @Deepthidharwar @sjug Any suggestions of documentation "tools" to use here, should we continue to use markdown files in a docs directory, maybe use the wiki feature of github and/or use some sort of other docs tool?

My opinion is that the markdown files will likely be the lowest impact to current work efforts and we could just create an organized structure in a docs directory to describe each workload and its vars.

**Comment by jmencak** [comment]
Totally agree with the issue.  Markdown files sound good.

**Comment by ekuric** [comment]
+1 , also I would recommend workloads/workloads/storage as separate location for storage tests

**Comment by akrzos** [comment]
At this point we now how a separate docs directory and separate README files per workload.  Closing this issue.
