### ISSUE TITLE
Verify pbench daemonset mounts are in use

### ISSUE THREAD

**Issue by akrzos** [openshift-scale/workloads#2]
There are several mounts in the pbench daemonsets that it is unclear if those mounts are in use or are left over cruft. 

Example: https://github.com/openshift-scale/workloads/blob/master/workloads/templates/pbench-master-ds.yml.j2#L44-L49

**Comment by akrzos** [comment]
@chaitanyaenr could you advise which mounts are still in use and which are no longer (if any so we can clean up the mounts)?

**Comment by chaitanyaenr** [comment]
@akrzos on it.

**Comment by akrzos** [comment]
@chaitanyaenr any updates here?

**Comment by akrzos** [comment]
Fixed with #31
