### ISSUE TITLE
Add Baseline Workload

### ISSUE THREAD

**Issue by akrzos** [openshift-scale/workloads#7]
@chaitanyaenr FYI

**Comment by akrzos** [comment]
Maybe we want to rename this concept into "resource measurement" workload, thoughts? (Have it provide the amount of resources required to run the cluster at its current state? Thus if you run it immediate after install, we can see the resources required on a brand new cluster and we can rerun it post running another workload without cleanup and see resources required with a specific amount of load.)

**Comment by chaitanyaenr** [comment]
@akrzos resource measurement workload sounds good to me.

**Comment by akrzos** [comment]
Issue resolved now.
